function GetCardJson(){
    
}


var carddata =[
    {
        "name":"", 
        "status":3,
        "type":"none",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"none",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":30,
        "type":"none",
        "class":"attack",
        "plusattack":false,
        "sponerate":1,
        "hitrate":30,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"none",
        "class":"defense",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"fire",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":70,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"fire",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":70,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"fire",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":70,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":50,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":50,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":50,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":40,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":40,
        "cost":0
    },
    {
        "name":"",
        "status":12,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":1,
        "hitrate":25,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"fire",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":9,
        "type":"water",
        "class":"attack",
        "plusattack":true,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"water",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"grass",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"grass",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"grass",
        "class":"attack",
        "plusattack":true,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"grass",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"grass",
        "class":"attack",
        "plusattack":true,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":1,
        "hitrate":50,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":3,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"grass",
        "class":"defense",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":1,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":3,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":7,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"item",
        "class":"HPheal",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"item",
        "class":"HPheal",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":5,
        "type":"item",
        "class":"MPheal",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"item",
        "class":"MPheal",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":15,
        "type":"item",
        "class":"MPheal",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":10,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":50,
        "cost":7
    },
    {
        "name":"",
        "status":10,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":50,
        "cost":7
    },
    {
        "name":"",
        "status":10,
        "type":"water",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":50,
        "cost":7
    },
    {
        "name":"",
        "status":10,
        "type":"water",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":50,
        "cost":7
    },
    {
        "name":"",
        "status":10,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":50,
        "cost":7
    },
    {
        "name":"",
        "status":10,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":50,
        "cost":7
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":75,
        "cost":5
    },
    {
        "name":"",
        "status":5,
        "type":"fire",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":75,
        "cost":5
    },
    {
        "name":"",
        "status":5,
        "type":"water",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":75,
        "cost":5
    },
    {
        "name":"",
        "status":5,
        "type":"water",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":75,
        "cost":5
    },
    {
        "name":"",
        "status":5,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":75,
        "cost":5
    },
    {
        "name":"",
        "status":5,
        "type":"grass",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":75,
        "cost":10
    },
    {
        "name":"",
        "status":12,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":30,
        "cost":10
    },
    {
        "name":"",
        "status":12,
        "type":"dark",
        "class":"attack",
        "plusattack":false,
        "sponerate":2,
        "hitrate":30,
        "cost":10
    },
    {
        "name":"",
        "status":10,
        "type":"none",
        "class":"HPheal",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":7
    },
    {
        "name":"",
        "status":8,
        "status2":4,
        "type":"none",
        "class":"both",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "status":2,
        "status2":9,
        "type":"none",
        "class":"both",
        "plusattack":false,
        "sponerate":1,
        "hitrate":100,
        "cost":0
    },
    {
        "name":"",
        "explanation":"現在の体力-1の2倍のダメージを与えることができる。使用後、体力は1になる。",
        "status":0,
        "type":"none",
        "class":"unique",
        "plusattack":false,
        "sponerate":1,
        "hitrate":50,
        "cost":0
    }
]